"""create initial schema

Revision ID: cc021e29fc12
Revises: 
Create Date: 2026-07-10 08:15:08.010625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc021e29fc12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_master',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('typical_unit', sa.String(length=30), nullable=True),
    sa.Column('shelf_life_days', sa.Integer(), nullable=True),
    sa.Column('is_pantry_staple', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('common_aliases', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name')
    )
    op.create_table('supported_chains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_name', sa.String(length=120), nullable=False),
    sa.Column('chain_slug', sa.String(length=120), nullable=False),
    sa.Column('has_weekly_circular', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('circular_refresh_day', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chain_slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supabase_user_id', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('goal', sa.String(length=30), server_default=sa.text("'eat_healthy'"), nullable=False),
    sa.Column('calorie_target', sa.Integer(), server_default=sa.text('2000'), nullable=False),
    sa.Column('protein_target', sa.Integer(), server_default=sa.text('100'), nullable=False),
    sa.Column('diet_type', sa.String(length=30), server_default=sa.text("'omnivore'"), nullable=False),
    sa.Column('allergies', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('cuisine_preferences', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('excluded_ingredients', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('skill_level', sa.String(length=20), server_default=sa.text("'intermediate'"), nullable=False),
    sa.Column('max_prep_time', sa.Integer(), server_default=sa.text('45'), nullable=False),
    sa.Column('household_size', sa.Integer(), server_default=sa.text('4'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supabase_user_id')
    )
    op.create_table('circular_fetches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('fetch_date', sa.Date(), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('image_keys', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['supported_chains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pantry_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('image_keys', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('ai_response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('items_detected', sa.Integer(), nullable=True),
    sa.Column('items_confirmed', sa.Integer(), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(length=10), nullable=True),
    sa.Column('prep_time_min', sa.Integer(), nullable=True),
    sa.Column('cook_time_min', sa.Integer(), nullable=True),
    sa.Column('total_time_min', sa.Integer(), nullable=True),
    sa.Column('servings', sa.Integer(), nullable=True),
    sa.Column('ingredients_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('instructions_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nutrition_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('why_this_recipe', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('cuisine', sa.String(length=50), nullable=True),
    sa.Column('ai_model', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shopping_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'active'"), nullable=False),
    sa.Column('total_known_cost', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deal_savings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('item_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('store_locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('store_name', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['supported_chains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deal_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chain_id', sa.Integer(), nullable=False),
    sa.Column('fetch_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(length=300), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('sale_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_unit', sa.String(length=50), nullable=True),
    sa.Column('regular_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('savings_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('deal_type', sa.String(length=30), nullable=True),
    sa.Column('deal_details', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('purchase_limit', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('matched_ingredient_id', sa.Integer(), nullable=True),
    sa.Column('match_confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sale_price > 0', name='ck_deal_cache_sale_price_positive'),
    sa.ForeignKeyConstraint(['chain_id'], ['supported_chains.id'], ),
    sa.ForeignKeyConstraint(['fetch_id'], ['circular_fetches.id'], ),
    sa.ForeignKeyConstraint(['matched_ingredient_id'], ['ingredient_master.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_deal_cache_chain_validity', 'deal_cache', ['chain_id', 'valid_from', 'valid_to'], unique=False)
    op.create_index('ix_deal_cache_matched_ingredient', 'deal_cache', ['matched_ingredient_id'], unique=False)
    op.create_table('pantry_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('quantity_estimate', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('brand', sa.String(length=100), nullable=True),
    sa.Column('freshness', sa.String(length=20), server_default=sa.text("'good'"), nullable=False),
    sa.Column('estimated_expiry', sa.Date(), nullable=True),
    sa.Column('is_staple', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('scan_id', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ),
    sa.ForeignKeyConstraint(['scan_id'], ['pantry_scans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pantry_items_user_active', 'pantry_items', ['user_id', 'is_active'], unique=False)
    op.create_table('user_stores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('store_location_id', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['store_location_id'], ['store_locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'store_location_id', name='uq_user_store')
    )
    op.create_table('week_recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('is_cooked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('cooked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'recipe_id', 'week_start', name='uq_week_recipe')
    )
    op.create_index('ix_week_recipes_user_week', 'week_recipes', ['user_id', 'week_start'], unique=False)
    op.create_table('shopping_list_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('buy_quantity', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_on_sale', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('regular_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('from_recipes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_checked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_manual_add', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deal_cache.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredient_master.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['shopping_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shopping_list_items_list_checked', 'shopping_list_items', ['list_id', 'is_checked'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shopping_list_items_list_checked', table_name='shopping_list_items')
    op.drop_table('shopping_list_items')
    op.drop_index('ix_week_recipes_user_week', table_name='week_recipes')
    op.drop_table('week_recipes')
    op.drop_table('user_stores')
    op.drop_index('ix_pantry_items_user_active', table_name='pantry_items')
    op.drop_table('pantry_items')
    op.drop_index('ix_deal_cache_matched_ingredient', table_name='deal_cache')
    op.drop_index('ix_deal_cache_chain_validity', table_name='deal_cache')
    op.drop_table('deal_cache')
    op.drop_table('store_locations')
    op.drop_table('shopping_lists')
    op.drop_table('recipes')
    op.drop_table('pantry_scans')
    op.drop_table('circular_fetches')
    op.drop_table('users')
    op.drop_table('supported_chains')
    op.drop_table('ingredient_master')
    # ### end Alembic commands ###
